[user]
name = 'Alejandro Fernández Gómez'
email = 'antarticonorte@gmail.com'

[ui]
editor = "hx"
default-command = 'log'
diff.tool = 'difft'
# diff-editor = 'filemerge'
# merge-editor = 'filemerge'
diff-instructions = false

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[merge-tools.opendiff]
diff-args = ["$left", "$right"]
edit-args = ["$left", "$right", "-merge", "$output"]
merge-args = ["$left", "$right", "-ancestor $base", "-merge $output"]

# See https://gist.github.com/afgomez/57abc71290296816ddbd567b39e27f17
[merge-tools.filemerge]
program = "filemerge"
diff-args = ["-left", "$left", "-right", "$right"]
edit-args = ["-left", "$left", "-right", "$right", "-merge", "$output"]
merge-args = ["-left", "$left", "-right", "$right", "-ancestor", "$base", "-merge", "$output"]

[experimental-advance-branches]
# enabled-branches = ["glob:*"]
# disabled-branches = ["main", "glob:push-*"]
