set -g default-terminal "xterm-256color"
set -sg escape-time 0

set -g history-limit 50000

# Easily reload configuration
bind-key R source-file ~/.tmux.conf \; display "tmux config reloaded!"

# Starts windows in 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Quick close
bind-key & kill-window
bind-key x kill-pane


# Vim-like split bindings
bind s split-window -v
bind v split-window -h

# Pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse settings
set -g mouse on

bind -T copy-mode WheelUpPane send -N1 -X scroll-up
bind -T copy-mode-vi WheelUpPane send -N1 -X scroll-up
bind -T copy-mode WheelDownPane send -N1 -X scroll-down
bind -T copy-mode-vi WheelDownPane send -N1 -X scroll-down

# Track activity on windows
setw -g monitor-activity on
setw -g monitor-bell on
set -g visual-activity off

# Theme

## Status bar
set -g status-style fg=white,bg=colour233

set -g status-left '#[bg=colour237,fg=colour247] ❐ #S #[fg=colour237,bg=colour233]'
set -g status-right '#[fg=colour237,bg=colour233]#[fg=colour247,bg=colour237] %d %b  ⌚️ %H:%M '

set -g window-status-format ' #I #W '
set -g window-status-current-format "#[fg=colour233,bg=colour39]#[fg=colour16,bg=colour39,noreverse,bold] #I  #W #[fg=colour39,bg=colour233,nobold]"
set -g window-status-activity-style fg=yellow,italics
setw -g window-status-bell-style fg=red,bg=default,blink


## Messages bar
set -g message-style fg=colour16,bg=colour221,bold






