set -g default-terminal "xterm-256color"

# Starts windows in 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Renumber when a window is closed
set-option -g renumber-windows on

# Quick close
bind-key & kill-window
bind-key x kill-pane

# Vim-like split bindings
bind '"' split-window -v -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Fade inactive panes
set -g window-style fg=colour243
set -g window-active-style fg=white

# set the pane border colors
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour245

# Mouse settings
set -g mouse on

bind -T copy-mode WheelUpPane send -N1 -X scroll-up
bind -T copy-mode-vi WheelUpPane send -N1 -X scroll-up
bind -T copy-mode WheelDownPane send -N1 -X scroll-down
bind -T copy-mode-vi WheelDownPane send -N1 -X scroll-down

# Track activity on windows
setw -g monitor-activity on
setw -g monitor-bell on
set -g visual-activity off

# Theme

## Status bar
set -g status-style fg=white,bg=colour235

set -g status-left-length 20
set -g status-left '#[bg=colour237,fg=colour247] ❐ #S #[fg=colour237,bg=colour235]'
set -g status-right '#[fg=colour237,bg=colour235]#[fg=colour247,bg=colour237] %d %b  %H:%M '

set -g window-status-format ' #I #W '
set -g window-status-current-format "#[fg=colour235,bg=blue]#[fg=white,bg=blue,noreverse,bold] #I  #W #[fg=blue,bg=colour235,nobold]"
set -g window-status-activity-style fg=yellow,italics
setw -g window-status-bell-style fg=red,bg=default,blink


## Messages bar
set -g message-style fg=colour16,bg=colour221,bold

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
